/*
 =========================================================
 * Stop-Uncle.Net
 =========================================================

 * License: MIT
 * Copyright 2020 TeamWV (https://teamwv.ml)

 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/

#테이블 구조
CREATE TABLE aje_db
( 
  _id INT PRIMARY KEY AUTO_INCREMENT,
  que TEXT NOT NULL,
  answer TEXT NOT NULL
) ENGINE=INNODB;

#아재 개그 문제 데이터베이스
INSERT into aje_db (que, answer) VALUES('나무를 톱으로 캐면?', '트리케라톱스');
INSERT into aje_db (que, answer) VALUES('이광수가 스파에 들어가면?', '스파게리');
INSERT into aje_db (que, answer) VALUES('우유가 넘어지면?', '아야');
INSERT into aje_db (que, answer) VALUES('세발낙지가 탈모에 걸리면?', '한발낙지');
INSERT into aje_db (que, answer) VALUES('토끼가 강한 이유는?', '깡과 총이 있어서');
INSERT into aje_db (que, answer) VALUES('스님이 택시를 타고 하는 말은?', '절로가');
INSERT into aje_db (que, answer) VALUES('마블보다 4배 큰 기업은?', '넷마블');
INSERT into aje_db (que, answer) VALUES('오리가 옳다고 인정하면?', '덕수긍');
INSERT into aje_db (que, answer) VALUES('친일파 동물을 부르는 말은?', '애완용');
INSERT into aje_db (que, answer) VALUES('개들이 가장 싫어하는 절은?', '보신각');
INSERT into aje_db (que, answer) VALUES('노인과 바다를 3글자로 부르는 말은?', 'Sea에 틀');
INSERT into aje_db (que, answer) VALUES('언론통제를 다른 말로 하면?', '보도블럭');
INSERT into aje_db (que, answer) VALUES('만수르가 입원한 이유는?', '부 상당해서');
INSERT into aje_db (que, answer) VALUES('F가 애매한 이유는?', 'F = ma 이니까');
INSERT into aje_db (que, answer) VALUES('옷감을 울게 하는 만드는 것은?', '섬유유(ㅠㅠ)연제');
INSERT into aje_db (que, answer) VALUES('등 처먹고 사는 사람은?', '안마사');
INSERT into aje_db (que, answer) VALUES('부처가 먹는 음식은?', '전 부처 먹음');
INSERT into aje_db (que, answer) VALUES('애플이 망해가는 이유는?', 'Mac(막) 만들어서');
INSERT into aje_db (que, answer) VALUES('글씨를 피카츄로 지워도 되는 이유는?', '지우 개니까');
INSERT into aje_db (que, answer) VALUES('지니가 노란색이 되면?', '황지니');
INSERT into aje_db (que, answer) VALUES('인도는 지금 몇 시일까?', '인도네시아');
INSERT into aje_db (que, answer) VALUES('물고기를 가장 잘 낚는 일본인은?', '다나까');
INSERT into aje_db (que, answer) VALUES('과소비가 심한 동물은?', '사자');
INSERT into aje_db (que, answer) VALUES('슈퍼맨이 어렸을 때를 뭐라고 할까?', '슈퍼주니어');
INSERT into aje_db (que, answer) VALUES('가장 강한 세균은?', '대장균');
INSERT into aje_db (que, answer) VALUES('곰은 사과를 어떻게 먹을까?', '베어(Bear)먹음');
INSERT into aje_db (que, answer) VALUES('시간이 갈수록 환해지는 것은?', '흰머리');
INSERT into aje_db (que, answer) VALUES('학생들이 가장 싫어하는 피자는?', '책 피자');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 믿을 만한 오리는?', '미더덕');
INSERT into aje_db (que, answer) VALUES('"비가 내일 비행기로 LA에 간다"를 4글자로?', 'LA갈비');
INSERT into aje_db (que, answer) VALUES('도둑이 도둑질하러 가는 걸음걸이를 4글자로?', '털레털레');
INSERT into aje_db (que, answer) VALUES('소가 웃는 소리를 3글자로?', '우하하');
INSERT into aje_db (que, answer) VALUES('칼로 산 두개를 자르면?', '두산베어스');
INSERT into aje_db (que, answer) VALUES('낙엽이 애교를 부리면서 하는 말은?', '나기엽?');
INSERT into aje_db (que, answer) VALUES('모내기 기계가 고장이 나면?', '심기 불편');
INSERT into aje_db (que, answer) VALUES('옳지 못한 오리는?', '');
INSERT into aje_db (que, answer) VALUES('돼지고기가 금값인 이유는?', '돼지가 한 돈 가격 이라서');
INSERT into aje_db (que, answer) VALUES('비실이를 총으로 쏘면?', '탕비실');
INSERT into aje_db (que, answer) VALUES('탱글탱글한 피부를 만드는데 걸리는 시간은?', '수 분');
INSERT into aje_db (que, answer) VALUES('뼈가 있는 방은?', '골룸');
INSERT into aje_db (que, answer) VALUES('세계에서 가장 추운 바다는?', '썰렁해');
INSERT into aje_db (que, answer) VALUES('세계에서 가장 뜨거운 바다는?', '열바다');
INSERT into aje_db (que, answer) VALUES('늘 무엇인가를 찾고 있는 스님은?', '탐색중');
INSERT into aje_db (que, answer) VALUES('네일 아티스트들이 일찍 죽는 이유는?', '오늘 네일 해서');
INSERT into aje_db (que, answer) VALUES('갓 출가하여 열심히 수도생활하는 스님은?', '노력중');
INSERT into aje_db (que, answer) VALUES('나무를 주면 살고, 물을 주면 죽지 말라고 해도 죽는 것은?', '장작불');
INSERT into aje_db (que, answer) VALUES('가장 어렵게 지은 절은?', '우여곡절');
INSERT into aje_db (que, answer) VALUES('가난하지만 부자인 사람은?', '아버지와 아들');
INSERT into aje_db (que, answer) VALUES('로또복권 당첨 확률을 2배 올리는 방법은?', '두 장 산다.');
INSERT into aje_db (que, answer) VALUES('먹고살기 위해 찾는 책은?', '호구지책');
INSERT into aje_db (que, answer) VALUES('비가 올 때 하는 욕은?', 'byc');
INSERT into aje_db (que, answer) VALUES('바닷가에서는 해도 되는 욕은?', '해수욕');
INSERT into aje_db (que, answer) VALUES('머리에 총을 맞아도 살 수 있는 방법은?', '총알을 피한다.');
INSERT into aje_db (que, answer) VALUES('어떤 내기에도 져본 적이 없는 과학자는?', '다윈');
INSERT into aje_db (que, answer) VALUES('있을 수도 있고 없을 수도 있는 섬은?', '아마도');
INSERT into aje_db (que, answer) VALUES('세계에서 몸집에 제일 큰 여자의 이름은?', '태평양');
INSERT into aje_db (que, answer) VALUES('이 세상에 태어나 단 한 번만 먹고 입을 다물어 버리는 것은?', '편지봉투');
INSERT into aje_db (que, answer) VALUES('아무리 예뻐도 미녀라고 불리지 못하는 사람은?', '미남');
INSERT into aje_db (que, answer) VALUES('암탉은 어느 집에서 시집왔을까?', '꼬꼬댁');
INSERT into aje_db (que, answer) VALUES('화장실에 가면 소변과 대변 중 어느 것이 먼저 나올까?', '급한 것');
INSERT into aje_db (que, answer) VALUES('전주비빔밥보다 더 싱싱한 것은?', '이번주비빔밥');
INSERT into aje_db (que, answer) VALUES('흑인들은 검정색을 무엇이라고 할까?', '살색');
INSERT into aje_db (que, answer) VALUES('호랑이는 영어로 Tiger이다. 이 빠진 호랑이는?', 'Tigr');
INSERT into aje_db (que, answer) VALUES('홀로그램', '㎏ ㎏ ㎏ ㎏ g ㎏ ㎏ ㎏');
INSERT into aje_db (que, answer) VALUES('야! 필리핀 갈 때 돈 많이 가져가지 마!', '동남아');
INSERT into aje_db (que, answer) VALUES('컴퓨터가 고장 났을 때 읊는 시는?', '오륜가');
INSERT into aje_db (que, answer) VALUES('북한에 민주주의가 오겠어요?', '아오지요');
INSERT into aje_db (que, answer) VALUES('꽃이 병원에 가는 이유는?', '수술이 있어서');
INSERT into aje_db (que, answer) VALUES('큰 북 안에 작은북과 병아리를 넣으면 나는 소리는?', '쿵따라닥닥삐약삐약');
INSERT into aje_db (que, answer) VALUES('유부남이 제일 무서워하는 치킨은?', '마늘치킨');
INSERT into aje_db (que, answer) VALUES('파가 웃으면?', '파우치');
INSERT into aje_db (que, answer) VALUES('미용실에서 머리를 했는데 비싸게 받으면?', '바가지 머리');
INSERT into aje_db (que, answer) VALUES('아버지가 재혼을 세 번 했으면?', '엠넷');
INSERT into aje_db (que, answer) VALUES('막대기가 넘어지면?', '어쿠스틱');
INSERT into aje_db (que, answer) VALUES('수상함과 잠수함의 통신 내용은?', '너수상함, 나잠수함');
INSERT into aje_db (que, answer) VALUES('대전에서 응급상황이 발생하면?', '이"머전"씨');
INSERT into aje_db (que, answer) VALUES('발렌타인데이에 자기가 직접 초콜릿 사면?', '발렌본인데이');
INSERT into aje_db (que, answer) VALUES('자기가 돌체의 자식이란 걸 깨달은 입양아가 한 말은?', '돌체 앤 가봐 나');
INSERT into aje_db (que, answer) VALUES('국회의원을 3글자로?', '9K1');
INSERT into aje_db (que, answer) VALUES('공이 너무 많아서 남아도는 나라는?', '남아공');
INSERT into aje_db (que, answer) VALUES('인도주의와 반대되는 사상은?', '파키스탄주의');
INSERT into aje_db (que, answer) VALUES('꽃들의 전쟁은?', '플라워');
INSERT into aje_db (que, answer) VALUES('갑자기 난 이빨은?', '써든니');
INSERT into aje_db (que, answer) VALUES('정부에서 뭐만 했다 하면 국민들이 나서서 반대하는 나라는?', '불가리아');
INSERT into aje_db (que, answer) VALUES('식빵과 잼이 싸우면?', '잼이 발린다');
INSERT into aje_db (que, answer) VALUES('김태희가 드라이브를 하다가 동생 이완을 만나고 나서 한 말은?', '타이완');
INSERT into aje_db (que, answer) VALUES('아들이 방에서 보노보노를 보고 있었다. 그걸 본 엄마가 하는 말은?', '보노보노보노?');
INSERT into aje_db (que, answer) VALUES('포테이토칩의 마음은?', '농심');
INSERT into aje_db (que, answer) VALUES('미친 쥐를 4글자로?', '광마우스');
INSERT into aje_db (que, answer) VALUES('배고플 때 쏘는 파는?', '배고파');
INSERT into aje_db (que, answer) VALUES('반지의 제왕을 둘로 나누면?', '제왕절개');
INSERT into aje_db (que, answer) VALUES('브라질 사람들이 먹는 아이스크림은?', '쌈바');
INSERT into aje_db (que, answer) VALUES('추울 때 따뜻하게 해주는 아이스크림은?', '잠바');
INSERT into aje_db (que, answer) VALUES('산토끼의 반대말은?', '죽은토끼');
INSERT into aje_db (que, answer) VALUES('남자가 제일 좋아하는 집은?', '계집');
INSERT into aje_db (que, answer) VALUES('4마리의 고양이 괴물은?', '포켓몬스터');
INSERT into aje_db (que, answer) VALUES('목에 글씨를 적으면?', '목적어');
INSERT into aje_db (que, answer) VALUES('축구공이 굴러갈 때 사람들의 반응은?', '공감');
INSERT into aje_db (que, answer) VALUES('김수미가 유독 고소고발을 많이 당하는 이유는?', 'Sue me');
INSERT into aje_db (que, answer) VALUES('고구려에 야근수당이 없던 이유는?', '고구려는 약은 수, 당을 싫어했기 때문');
INSERT into aje_db (que, answer) VALUES('망고의 옛날 이름은?', 'manwent');
INSERT into aje_db (que, answer) VALUES('소를 수출할 때 꼭 필요한 것은?', '소비자');
INSERT into aje_db (que, answer) VALUES('부처님이 일어서면서 하는 말은?', '선불입니다');
INSERT into aje_db (que, answer) VALUES('학력이 떨어지는 스님을 2글자로?', '중졸');
INSERT into aje_db (que, answer) VALUES('자동차가 울면?', '잉카');
INSERT into aje_db (que, answer) VALUES('바람이 귀엽게 부는 곳은 어디일까?', '분당');
INSERT into aje_db (que, answer) VALUES('국내에 마블보다 4배 큰 기업은?', '넷마블');
INSERT into aje_db (que, answer) VALUES('차 열쇠 색깔은?', '카키색');
INSERT into aje_db (que, answer) VALUES('다정함의 반대말은?', '선택장애');
INSERT into aje_db (que, answer) VALUES('유모차 타면 긴장되는 이유는?', '애가타서');
INSERT into aje_db (que, answer) VALUES('바람의 엉덩이를 부르는 말은?', '풍뎅이');
INSERT into aje_db (que, answer) VALUES('고양이를 정말 좋아하는 종교는?', 'Catholic');
INSERT into aje_db (que, answer) VALUES('활을 무기로 쓰면 반드시 이기는 기간은?', '활로윈');
INSERT into aje_db (que, answer) VALUES('먹지 않아도 맛이 단 것은?', '단잠');
INSERT into aje_db (que, answer) VALUES('바닷가에서는 해도 되는 욕은?', '해수욕');
INSERT into aje_db (que, answer) VALUES('어떤 내기에도 져본 적이 없는 과학자는?', '다윈');
INSERT into aje_db (que, answer) VALUES('있을 수도 있고 없을 수도 있는 섬은?', '아마도');
INSERT into aje_db (que, answer) VALUES('세계에서 몸집에 제일 큰 여자의 이름은?', '태평양');
INSERT into aje_db (que, answer) VALUES('아무도 믿을 수 없다는 사람이 가장 믿는 신은?', '자기 자신');
INSERT into aje_db (que, answer) VALUES('서로 진짜라고 우기는 신은?', '옥신 각신');
INSERT into aje_db (que, answer) VALUES('아침마다 절 받는 것은?', '세면대');
INSERT into aje_db (que, answer) VALUES('암탉은 어느 집에서 시집왔을까?', '꼬꼬댁');
INSERT into aje_db (que, answer) VALUES('피가 아프면?', '피식');
INSERT into aje_db (que, answer) VALUES('선풍기가 바람을 피면?', '풍기문란');
INSERT into aje_db (que, answer) VALUES('모자를 때릴 수 있는 도구?', '캡처 도구');
INSERT into aje_db (que, answer) VALUES('꽃이 병원에 가는 이유는?', '수술이 있어서');
INSERT into aje_db (que, answer) VALUES('죽을 먹다가 실수로 엎으면?', '전복죽');
INSERT into aje_db (que, answer) VALUES('그물낚시를 하면 물고기가 안 잡히는 이유는?', '망쳤기 때문');
INSERT into aje_db (que, answer) VALUES('가까이 있는 것을 못 보는 사람은?', '원시인');
INSERT into aje_db (que, answer) VALUES('문어가 지면?', '무너 진다');
INSERT into aje_db (que, answer) VALUES('결혼을 두 번 하면?', '2혼');
INSERT into aje_db (que, answer) VALUES('가장 비싼 돌은?', '일석이조');
INSERT into aje_db (que, answer) VALUES('프로들의 느낌을 3글자로?', '프로필');
INSERT into aje_db (que, answer) VALUES('선택을 하지 않는 나라는?', '앙골라');
INSERT into aje_db (que, answer) VALUES('비의 어린 시절은?', '아이비');
INSERT into aje_db (que, answer) VALUES('쥐가 낚싯줄에 걸리면?', '미끼마우스');
INSERT into aje_db (que, answer) VALUES('긴장 풀 때 먹는 약은?', '안정환');
INSERT into aje_db (que, answer) VALUES('산이 안 움직이면?', '부동산');
INSERT into aje_db (que, answer) VALUES('양과 말을 교배시켰을 때 태어나는 종은?', '양말');
INSERT into aje_db (que, answer) VALUES('반지의 제왕을 둘로 나누면?', '제왕절개');
INSERT into aje_db (que, answer) VALUES('바른 생활만 하는 쥐는?', '건전쥐');
INSERT into aje_db (que, answer) VALUES('아빠의 귀를 비디오카메라로 찍으면?', '부귀영화');
INSERT into aje_db (que, answer) VALUES('목에 글씨를 적으면?', '목적어');
INSERT into aje_db (que, answer) VALUES('축구공이 굴러갈 때 사람들의 반응은?', '공감');
INSERT into aje_db (que, answer) VALUES('산소를 기피하는 사람을 5글자로?', '오뚜 기피자');
INSERT into aje_db (que, answer) VALUES('초인종이 귀한 나라는?', '벨기에');
INSERT into aje_db (que, answer) VALUES('개가 재채기를 하면?', '개추');
INSERT into aje_db (que, answer) VALUES('스님이 택시를 타고 한말은?', '절로가');
INSERT into aje_db (que, answer) VALUES('유모차 타면 긴장되는 이유는?', '애가타서');
INSERT into aje_db (que, answer) VALUES('천을 서로 비비면?', '천문대');
INSERT into aje_db (que, answer) VALUES('유모차 타면 긴장되는 이유는?', '애가타서');
INSERT into aje_db (que, answer) VALUES('투명인간은 몇명이나 있을까', '2명');
INSERT into aje_db (que, answer) VALUES('앉으면 졸린 이유는?', '안자서');
INSERT into aje_db (que, answer) VALUES('이자 없이 꾸는 것은?', '꿈');
INSERT into aje_db (que, answer) VALUES('자동차가 죽으면 묻히는 무덤은?', '부르릉');
INSERT into aje_db (que, answer) VALUES('땅중에서 가장 멋있는 땅은?', '개간지');
INSERT into aje_db (que, answer) VALUES('냉전의 반댓말은?', '더워');
INSERT into aje_db (que, answer) VALUES('러시아 사람이 점프하면?', '스키점프');
INSERT into aje_db (que, answer) VALUES('모든 사람이 물건을 사기만 했던 나라는?', '소비에트');
INSERT into aje_db (que, answer) VALUES('공이 웃으면?', '풋볼');
INSERT into aje_db (que, answer) VALUES('숲속에서 자라는 것 중 가장 야한 것은?', '버섯');
INSERT into aje_db (que, answer) VALUES('자동차가 울면?', '잉카');
INSERT into aje_db (que, answer) VALUES('딸기가 회사에서 잘리면?', '딸기시럽');
INSERT into aje_db (que, answer) VALUES('바람이 귀엽게 부는 곳은 어디일까?', '분당');
INSERT into aje_db (que, answer) VALUES('자가용의 반대말은?', '커용');
INSERT into aje_db (que, answer) VALUES('뎅뎅뎅뎅뎅을 두글자로 줄이면?', '오뎅');
INSERT into aje_db (que, answer) VALUES('푸가 넘어지면?', '쿵푸');
INSERT into aje_db (que, answer) VALUES('할아버지들이 제일 좋아하는 돈은?', '할머니');
INSERT into aje_db (que, answer) VALUES('피카츄가 담배를 주우면서 하는 말은?', '피까');
INSERT into aje_db (que, answer) VALUES('모든 사람을 일어나게 하는 숫자는?', '다섯');
INSERT into aje_db (que, answer) VALUES('이 세상에서 가장 멋진 사람은?', '나');
INSERT into aje_db (que, answer) VALUES('자동차를 톡하고 치면?', '카톡');
INSERT into aje_db (que, answer) VALUES('다리미가 좋아하는 음 식은?', '피자');
INSERT into aje_db (que, answer) VALUES('제일 폭발하기 쉬운 나라는?', '부탄');
INSERT into aje_db (que, answer) VALUES('뽑으면 우는 식물은?', '우엉');
INSERT into aje_db (que, answer) VALUES('광부가 가장 많은 나라는?', '케냐');
INSERT into aje_db (que, answer) VALUES('사람이 울면?', '흑인');
INSERT into aje_db (que, answer) VALUES('시가 리얼하면?', '시리얼');
INSERT into aje_db (que, answer) VALUES('소나무가 삐지면?', '칫솔');
INSERT into aje_db (que, answer) VALUES('우유가 아프면?', '앙팡');
INSERT into aje_db (que, answer) VALUES('등쳐먹고 사는 사람이 누군지 알아?', '안마사');
INSERT into aje_db (que, answer) VALUES('소가 불에 타면?', '탄소');
INSERT into aje_db (que, answer) VALUES('오리가 얼면?', '언덕');
INSERT into aje_db (que, answer) VALUES('가장 비싼 새는?', '백조');
INSERT into aje_db (que, answer) VALUES('땅이 어떻게 우는지 알아?', '흙흙');
INSERT into aje_db (que, answer) VALUES('수박 한 통에 오천 원인데, 두통엔?', '게보린');
INSERT into aje_db (que, answer) VALUES('맥주가 죽기 전에 남긴 말은?', '유언비어');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 가난한 왕은?', '최저임금');
INSERT into aje_db (que, answer) VALUES('칼이 정색하면?', '검정색');
INSERT into aje_db (que, answer) VALUES('가수 설운도 씨가 옷을 벗는 순서가 어떻게  될까?', '상하의');
INSERT into aje_db (que, answer) VALUES('항상 미안해하는 연예인은?', '지성');
INSERT into aje_db (que, answer) VALUES('반성문을 영어로 하면?', '글로벌');
INSERT into aje_db (que, answer) VALUES('세종대왕이 나온 고등학교는?', '가갸거겨고교');
INSERT into aje_db (que, answer) VALUES('새우가 주인공인 드라마는?', '대하드라마');
INSERT into aje_db (que, answer) VALUES('화장실에서 금방 나온 사람은?', '일본사람');
INSERT into aje_db (que, answer) VALUES('전 세계에서 회를 가장 잘 뜨는 곳은?', '회전문');
INSERT into aje_db (que, answer) VALUES('소금의 유통기한은 언제까지?', '천일염');
INSERT into aje_db (que, answer) VALUES('왕이 궁에 가기 싫을 때 하는 말은?', '궁시렁궁시렁');
INSERT into aje_db (que, answer) VALUES('차가 다니는 도로에 갑자기 사람이 뛰어들면?', '카놀라유');
INSERT into aje_db (que, answer) VALUES('신발이 화가 나면?', '신발끈');
INSERT into aje_db (que, answer) VALUES('고등학생이 싫어하는 나무는?', '야자나무');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 억울한 도형은?', '원통');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 지루한 중학교가 뭔지 알아?', '로딩중');
INSERT into aje_db (que, answer) VALUES('서울이 추우면?', '서울시립대');
INSERT into aje_db (que, answer) VALUES('정말 큰 학은?', '대학');
INSERT into aje_db (que, answer) VALUES('가장 야한 가수가 누구게?', '다비치');
INSERT into aje_db (que, answer) VALUES('어부들이 싫어하는 사람은?', '배철수');
INSERT into aje_db (que, answer) VALUES('얼음이 죽으면?', '다이빙');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 쉬운 숫자는?', '십구만');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 뜨거운 바다는?', '열받아');
INSERT into aje_db (que, answer) VALUES('인천 앞바다의 반대는?', '인천 엄마다');
INSERT into aje_db (que, answer) VALUES('누룽지를 영어로 하면?', '바비브라운');
INSERT into aje_db (que, answer) VALUES('가는 말이 고우면 오는 말은?', 'COME');
INSERT into aje_db (que, answer) VALUES('높은 곳에서 애를 낳는 동물은?', '하이에나');
INSERT into aje_db (que, answer) VALUES('딸기가 도망가면?', '딸기잼');
INSERT into aje_db (que, answer) VALUES('남자는 힘! 여자는?', '헐');
INSERT into aje_db (que, answer) VALUES('자동차가 3대 있으면?', '스리랑카');
INSERT into aje_db (que, answer) VALUES('아이스크림이 죽었다. 왜 죽었을까?', '차가와서');
INSERT into aje_db (que, answer) VALUES('배드민턴 동호회 에서 편파판정이 제일 심한 연예인은?', '유아인');
INSERT into aje_db (que, answer) VALUES('사람이 죽지 않는 산맥은?', '안데스산맥');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 긴 음식은?', '참기름');
INSERT into aje_db (que, answer) VALUES('참기름 다음으로 긴  음식은?', '들기름');
INSERT into aje_db (que, answer) VALUES('검도를 하다가 죽었다. 왜 죽었을까?', '죽도록 맞아서');
INSERT into aje_db (que, answer) VALUES('바나나가 웃으면?', '바나나킥');
INSERT into aje_db (que, answer) VALUES('바나나우유가 웃으면?', '빙그레');
INSERT into aje_db (que, answer) VALUES('아몬 드가 죽으면?', '다이아몬드');
INSERT into aje_db (que, answer) VALUES('사과가 웃으면?', '풋사과');
INSERT into aje_db (que, answer) VALUES('펭귄이 다니는 중학교는?', '냉방중');
INSERT into aje_db (que, answer) VALUES('펭귄이 다니는 고등학교는?', '냉장고');
INSERT into aje_db (que, answer) VALUES('대통령선거의 반대말은?', '대통령앉은거');
INSERT into aje_db (que, answer) VALUES('고기 먹을 때마다 따라오는 개는?', '이쑤시개');
INSERT into aje_db (que, answer) VALUES('신사가 자기소개할 때 쓰는 말은?', '신사임당');
INSERT into aje_db (que, answer) VALUES('푸가 여러 마리 있으면?', '푸들');
INSERT into aje_db (que, answer) VALUES('추장보다 높은 사람은?', '고추장');
INSERT into aje_db (que, answer) VALUES('불에 타는 국사책을 세 글자로 하면?', '불국사');
INSERT into aje_db (que, answer) VALUES('한 입 베어먹은 사과는?', '파인애플');
INSERT into aje_db (que, answer) VALUES('병아리가 잘 먹는 약은?', '삐약');
INSERT into aje_db (que, answer) VALUES('비가 자기소개 할 때 하는 말은?', '나비야');
INSERT into aje_db (que, answer) VALUES('텔레토비에서 뽀가 떠나면?', '뽀빠이');
INSERT into aje_db (que, answer) VALUES('도둑이 가장 싫어하는 아이스크림은?', '누가바');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 뜨거운 과일은?', '천도복숭아');
INSERT into aje_db (que, answer) VALUES('피자가 놀 라면?', '피자헛');
INSERT into aje_db (que, answer) VALUES('호주의 돈은?', '호주머니');
INSERT into aje_db (que, answer) VALUES('"미소"의 반대말은?', '당기소');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 장사를 잘 하는 동물은?', '판다');
INSERT into aje_db (que, answer) VALUES('"당신은 비를 아십니 까?"를 네 글자로 줄이면?', '너비아니');
INSERT into aje_db (que, answer) VALUES('물고기의 반대말은?', '불고기');
INSERT into aje_db (que, answer) VALUES('빵이 시골로 간 까닭은?', '소보로');
INSERT into aje_db (que, answer) VALUES('처음 만나는 소가 하는 말은?', '반갑소');
INSERT into aje_db (que, answer) VALUES('소녀시대가 티를 팔다가 지나가는 아저씨가 하는 말은?', '티파니');
INSERT into aje_db (que, answer) VALUES('소녀시대가 타고 다니는 차는?', '제시카');
INSERT into aje_db (que, answer) VALUES('고양이를 무서워하지 않는 쥐는?', '박쥐');
INSERT into aje_db (que, answer) VALUES('장사꾼들이 싫어하는 경기는?', '불경기');
INSERT into aje_db (que, answer) VALUES('"개가 사람을 가르친다"를 네 글자로 하면?', '개인지도');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 달콤한 술은?', '입술');
INSERT into aje_db (que, answer) VALUES('도둑이 가장 좋아하는 아이스크림은?', '보석바');
INSERT into aje_db (que, answer) VALUES('인도는 지금 몇 시일까?', '인도네시아');
INSERT into aje_db (que, answer) VALUES('호랑이가 오토바이를 타고 가고 있었다. 그런데 토끼가 있는 것이었다. 이때 호랑이가 토끼에게 하는 말은?', '타이거');
INSERT into aje_db (que, answer) VALUES('사람의 옷을 벗게 할 수 있는 식물은?', '버섯');
INSERT into aje_db (que, answer) VALUES('개와 오랑우탄이 결혼해서 낳는 것은?', '오랑캐');
INSERT into aje_db (que, answer) VALUES('병신들만 사는 나라는?', '네팔');
INSERT into aje_db (que, answer) VALUES('송해가 샤워하면?', '뽀송해');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 빠른 닭은?', '후다닥');
INSERT into aje_db (que, answer) VALUES('쥐가 네마리 모이면 무엇이 될까?', '쥐포');
INSERT into aje_db (que, answer) VALUES('오른손으로는 들어도 왼손으로는 들지 못하는 것은?', '왼손');
INSERT into aje_db (que, answer) VALUES('가장 뜨거운 전화는?', '화상전화');
INSERT into aje_db (que, answer) VALUES('포도가 자기소개 하면?', '포도당');
INSERT into aje_db (que, answer) VALUES('뱀에 불이 붙으면?', '뱀파이어');
INSERT into aje_db (que, answer) VALUES('푸른소가 용을 구하면?', '청소용구함');
INSERT into aje_db (que, answer) VALUES('어린 물고기는?', '영어');
INSERT into aje_db (que, answer) VALUES('과소비가 심한 동물은?', '사자');
INSERT into aje_db (que, answer) VALUES('마녀가 높이 올라가면?', '위치 에너지가 증가함');
INSERT into aje_db (que, answer) VALUES('사슴의 눈이 좋으면?', '굿 아이디 어(Good eye deer)');
INSERT into aje_db (que, answer) VALUES('미국이 싫으면?', '아메리카노');
INSERT into aje_db (que, answer) VALUES('형을 완전 좋아하는 동생은?', '형광팬');
INSERT into aje_db (que, answer) VALUES('날마다 새로운 욕을 만들어 내는 도시는?', '뉴욕');
INSERT into aje_db (que, answer) VALUES('스타들이 싸우는 모습을 뭐라고 할까?', '스타워즈');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 잔인한 비빔밥은?', '산채비빔밥');
INSERT into aje_db (que, answer) VALUES('슈퍼맨이 어렸을 때를 뭐라고 할까?', '슈 퍼주니어');
INSERT into aje_db (que, answer) VALUES('사자를 잡아다 끓인 국은?', '동물의왕국');
INSERT into aje_db (que, answer) VALUES('세균 중 가장 센 세균은?', '대장균');
INSERT into aje_db (que, answer) VALUES('떡인데, 먹을 수 없는 떡은?', '그림의 떡');
INSERT into aje_db (que, answer) VALUES('곰은  사과를 어떻게 먹을까?', '베어먹음');
INSERT into aje_db (que, answer) VALUES('시간이 갈수록 환해지는 것은?', '흰머리');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 큰 콩은?', '홍콩');
INSERT into aje_db (que, answer) VALUES('꿩 먹고 알도 먹는 사람은?', '꿩 주인');
INSERT into aje_db (que, answer) VALUES('가장 기분좋은 바람은?', '신바람');
INSERT into aje_db (que, answer) VALUES('옷에 걸고 다니는 빵은?', '멜빵');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 행복한 바다는?', '사랑해');
INSERT into aje_db (que, answer) VALUES('산토끼의 반대말은?', '판토끼');
INSERT into aje_db (que, answer) VALUES('닭은 닭인데 먹시 못하는 닭은?', '까닭');
INSERT into aje_db (que, answer) VALUES('아무리 예뻐도 미녀라고 못하는 사람은?', '미남');
INSERT into aje_db (que, answer) VALUES('"타자"의 반대말은?', '안타');
INSERT into aje_db (que, answer) VALUES('아무리 빨 리 달려도 앞서가지 못하는 것은?', '자동차 뒷바퀴');
INSERT into aje_db (que, answer) VALUES('"창이 날라오니까 피해"를 세글자로 하면?', '창피해');
INSERT into aje_db (que, answer) VALUES('지방 흡입의 반대말은?', '수도권 배출');
INSERT into aje_db (que, answer) VALUES('입이 S자로 되어 있으면?', 'EBS');
INSERT into aje_db (que, answer) VALUES('설날에 용돈을 하나도 못 받으면?', '설거지');
INSERT into aje_db (que, answer) VALUES('당신이 기쁨을 느끼면?', '유희열');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 팔힘이  센 사람은?', '암스트롱');
INSERT into aje_db (que, answer) VALUES('중국인이 말한 1+1의 답은?', '이다해');
INSERT into aje_db (que, answer) VALUES('양이 높은 곳에 있으면?', '고양이');
INSERT into aje_db (que, answer) VALUES('키보다 크면?', '키위');
INSERT into aje_db (que, answer) VALUES('전화로 세운 건물은?', '콜로세움');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 외로운 왕은?', '솔로몬');
INSERT into aje_db (que, answer) VALUES('소가 감전사로 죽으면?', '우사인볼트');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 믿을 만한 오리는?', '미더덕');
INSERT into aje_db (que, answer) VALUES('고양이가 죽어서 지옥에 가면?', '헬로키티');
INSERT into aje_db (que, answer) VALUES('직접 만든 총은?', '손수건');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 멍청한 개는?', '무지개');
INSERT into aje_db (que, answer) VALUES('신하가 왕한테 공 던지면서 하는 말은?', '송구하옵니다 전하');
INSERT into aje_db (que, answer) VALUES('"체리야"하고 부르자 대답하길?', '체리블로썸');
INSERT into aje_db (que, answer) VALUES('모든 싱글들에게 짝은?', '벙글');
INSERT into aje_db (que, answer) VALUES('네 명이 오줌을 싸면?', '포뇨');
INSERT into aje_db (que, answer) VALUES('"비가 내일 비행기로 LA에 간다"를 4글자로 줄이면?', 'LA갈비');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 추운 바다의 이름은?', '썰렁해');
INSERT into aje_db (que, answer) VALUES('도둑이 도둑질하러 가는 걸음걸 이를 4글자로 줄이면?', '털레털레');
INSERT into aje_db (que, answer) VALUES('소가 웃는 소리를 세 글자로 줄이면?', '우하하');
INSERT into aje_db (que, answer) VALUES('사람이 3명만 들어갈 수 있는 차는?', '인삼차');
INSERT into aje_db (que, answer) VALUES('코끼리 2마리가 서로 싸워, 둘 다 코가 떨어져 나갔다면 어떻게 될까?', '끼리끼리');
INSERT into aje_db (que, answer) VALUES('귀는 귀인데 발 달린 귀는?', '당나귀');
INSERT into aje_db (que, answer) VALUES('깍으면 깍을수록 커지는 것은?', '구멍');
INSERT into aje_db (que, answer) VALUES('다섯은 당기고 다섯은 들어가는 것은?', '장갑');
INSERT into aje_db (que, answer) VALUES('먹으면 죽는데 안 먹을 수 없는 것은?', '나이');
INSERT into aje_db (que, answer) VALUES('이 세상에서 가장 큰 작은 문은?', '소문');
INSERT into aje_db (que, answer) VALUES('별 중에 가장 슬픈 별은?', '이별');
INSERT into aje_db (que, answer) VALUES('목수도 고칠 수 없는 집은?', '고집');
INSERT into aje_db (que, answer) VALUES('스타들이 싸우는 모습을 뭐라고 할까?', '스타워즈');
INSERT into aje_db (que, answer) VALUES('세계에서 몸집 이 제일 큰 여자의 이름은?', '태평양');
INSERT into aje_db (que, answer) VALUES('세상에서 기장 아름다운 개는?', '무지개');
INSERT into aje_db (que, answer) VALUES('입으로 먹지 않고 귀로 먹는 것은?', '욕');
INSERT into aje_db (que, answer) VALUES('집에서 매일 먹는  약은?', '치약');
INSERT into aje_db (que, answer) VALUES('묵은 묵인데 먹지 못하는 묵은?', '침묵');
INSERT into aje_db (que, answer) VALUES('하늘과 땅 사이에 있는 것은?', '과');
INSERT into aje_db (que, answer) VALUES('1 더하기 1은?', '노동');
INSERT into aje_db (que, answer) VALUES('2 더하기 2는?', '덧니');
INSERT into aje_db (que, answer) VALUES('아몬드가 죽으면?', '다이아몬드');
INSERT into aje_db (que, answer) VALUES('장님도 몰 수 있는 것은?', '꿈');
INSERT into aje_db (que, answer) VALUES('떼돈을 벌려면?', '목욕탕');
INSERT into aje_db (que, answer) VALUES('예쁜데 속이 텅 빈 여자는?', '마네킹');
INSERT into aje_db (que, answer) VALUES('앞과 뒤 가 똑같은 닐은?', '일요일');
INSERT into aje_db (que, answer) VALUES('사람이 즐겨 먹는 피는?', '커피');
INSERT into aje_db (que, answer) VALUES('알파벳은 모두 몇 글자인가?', '세글자');
INSERT into aje_db (que, answer) VALUES('용 2마리가 서로 죽도록 싸우는 모습을 5글자로 나타내면?', '용용죽겠지');
INSERT into aje_db (que, answer) VALUES('손님이 깍아 달라는 대로 다 깍아 주는 사람은?', '이발사');
INSERT into aje_db (que, answer) VALUES('가까워도 서로 못보고 사는 것은?', '눈');
INSERT into aje_db (que, answer) VALUES('개 중에 서 가장 큰 개는?', '안개');
INSERT into aje_db (que, answer) VALUES('탈 중에서 못 쓰는 탈은?', '배탈');
INSERT into aje_db (que, answer) VALUES('허수아비의 아들 이름은?', '허수');
INSERT into aje_db (que, answer) VALUES('잠자는 소는?', '주무소');
INSERT into aje_db (que, answer) VALUES('쥐가 네마리 모이면 무엇이 될까?', '쥐포');
INSERT into aje_db (que, answer) VALUES('호주의 떡은?', '호떡');
INSERT into aje_db (que, answer) VALUES('"보통"의 반댓말은?', '곱배기');
INSERT into aje_db (que, answer) VALUES('창으로 찌르려고 할 때 하는 말은?', '창피해?');
INSERT into aje_db (que, answer) VALUES('추운 겨울에 가장 많이 찾는 끈은?', '따끈따끈');
INSERT into aje_db (que, answer) VALUES('오뎅을 다섯 글자로 늘이면?', '뎅뎅뎅뎅뎅');
INSERT into aje_db (que, answer) VALUES('탤런트 최지우가 기르는 개 이름은?', '지우개');
INSERT into aje_db (que, answer) VALUES('많이 맞을수록 좋 은 것은?', '시험문제');
INSERT into aje_db (que, answer) VALUES('날마다 가슴에 흑심을 품고 있는 것은?', '연필');
INSERT into aje_db (que, answer) VALUES('눈사람의 반대말은?', '일어선사람');
INSERT into aje_db (que, answer) VALUES('물은 물인데 사람들이 가장 좋아하 는 물은?', '선물');
INSERT into aje_db (que, answer) VALUES('"딩동댕"의 반대는?', '땡');
INSERT into aje_db (que, answer) VALUES('눈 깜짝할 사이에 할 수 있는 일은?', '윙크');
INSERT into aje_db (que, answer) VALUES('꽃이 제일 좋아하는 벌은?', '재벌');
INSERT into aje_db (que, answer) VALUES('중학생과 고등 학생이 타는 차는?', '중고차');
INSERT into aje_db (que, answer) VALUES('거꾸로 들어도 바로 보이는 것은?', '거울');
INSERT into aje_db (que, answer) VALUES('남이 이상해야 먹고 사는 사람은?', '치과의사');
INSERT into aje_db (que, answer) VALUES('"덥다. 덥다."하면서 땀을 흘리는데 땀을 수록 작아지는 것은?', '얼음');
INSERT into aje_db (que, answer) VALUES('물에서 태어났으면서도 물에 들어가면 죽는 것은?', '소금');
INSERT into aje_db (que, answer) VALUES('문은 문인데, 사람은 드나들 수  없고 이리저리 돌아다니는 문은?', '소문');
INSERT into aje_db (que, answer) VALUES('둘어가는 구멍은 하나인데 나오는 구멍은 둘인 것은?', '바지');
INSERT into aje_db (que, answer) VALUES('바다와 육지 사이에 있는것은?', '와');
INSERT into aje_db (que, answer) VALUES('손님이 올 때마다 끌려 나오는 것은?', '방석');
INSERT into aje_db (que, answer) VALUES('어른과 아이가 길을 가는데 아이는 그 아이를 아버지가 아니라고 하고, 어른은 그 아이가 아들이 라고 한다. 이 어른은 누구일까?', '어머니');
INSERT into aje_db (que, answer) VALUES('언제나 잘못을 비는 나무는?', '사과나무');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 더러운 강은?', '요강');
INSERT into aje_db (que, answer) VALUES('귀는 귀인데 못 듣는 귀는?', '뼈다귀');
INSERT into aje_db (que, answer) VALUES('굶는 사람이 많은 나라는?', '헝가리');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 달콤한 술은?', '입술');
INSERT into aje_db (que, answer) VALUES('말은 말인데 타지 못하는 말은?', '거짓말');
INSERT into aje_db (que, answer) VALUES('차도가 없는 나라는?', '인도');
INSERT into aje_db (que, answer) VALUES('"고추잠자리"를 2자로 줄이면?', '팬티');
INSERT into aje_db (que, answer) VALUES('항상 같은 길로만 다니는 것은?', '기차');
INSERT into aje_db (que, answer) VALUES('마른 옷은 벗고 젖은 옷만 입는  것은?', '빨랫줄');
INSERT into aje_db (que, answer) VALUES('사람들이 가장 많이 내는 소리는?', '숨소리');
INSERT into aje_db (que, answer) VALUES('행주와 가장 친한 거지는?', '설거지');
INSERT into aje_db (que, answer) VALUES('"아이추워"의 반대말은?', '어른더워');
INSERT into aje_db (que, answer) VALUES('길 거리에서 시주를 받는 스님들을 무슨 중이라고 할까?', '영업중');
INSERT into aje_db (que, answer) VALUES('많이 먹을수록 화나는 것은?', '욕');
INSERT into aje_db (que, answer) VALUES('언제나 말다툼이 있는 곳은?', '경마장');
INSERT into aje_db (que, answer) VALUES('경마장에서 하는 장난은?', '말장난');
INSERT into aje_db (que, answer) VALUES('돼지가 열 받으면 어떻게 되나?', '바베큐');
INSERT into aje_db (que, answer) VALUES('공부해서 남주는 사람은?', '교사');
INSERT into aje_db (que, answer) VALUES('사온다고 하면서도 못사오는  것은?', '못');
INSERT into aje_db (que, answer) VALUES('책은 책인데 읽을 수 없는 책은?', '주책');
INSERT into aje_db (que, answer) VALUES('"아홉 명의 자식들"을 세 글자로 줄이면?', '아이구');
INSERT into aje_db (que, answer) VALUES('사람이 즐겨 먹는 제비는?', '수제비');
INSERT into aje_db (que, answer) VALUES('세싱에서 가장 큰 코는?', '멕시코');
INSERT into aje_db (que, answer) VALUES('수학을 한글자로 줄이면?', '솩');
INSERT into aje_db (que, answer) VALUES('공중에서 사람들이 가장 좋아하는 공은?', '성공');
INSERT into aje_db (que, answer) VALUES('타이타닉의 구명보트에는 몇 명이 탈 수 있을까?', '9명');
INSERT into aje_db (que, answer) VALUES('죽이다의 반대말은?', '밥이다');
INSERT into aje_db (que, answer) VALUES('어두울 때면 우리 머리를 풀어 헤치고 물을 흘리는 것은?', '양초');
INSERT into aje_db (que, answer) VALUES('진짜 새의 이름은 무엇일가요?', '참새');
INSERT into aje_db (que, answer) VALUES('청소하는 여자를 세자로 줄이면?', '청소년');
INSERT into aje_db (que, answer) VALUES('다리 두개에 갈비뼈만 앙상한것은?', '사다리');
INSERT into aje_db (que, answer) VALUES('눈 오는 날만 일하 는 사람은?', '안과의사');
INSERT into aje_db (que, answer) VALUES('앞으로 나가면 지고 뒤로 물러나면 이기는 것은?', '줄다리기');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 빨리 자는 사람은?', '이미자');
INSERT into aje_db (que, answer) VALUES('자꾸 맞아야 사는 것은?', '팽이');
INSERT into aje_db (que, answer) VALUES('닦을 수록 더러워지는 것은?', '걸레');
INSERT into aje_db (que, answer) VALUES('얼굴은 여섯이고 눈은 21인 것은?', '주사위');
INSERT into aje_db (que, answer) VALUES('앉으면 높아지고 서면 낮아지는 것 은?', '천장');
INSERT into aje_db (que, answer) VALUES('다 자랐는데도 자라라고 하는 것은?', '자라');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 행복한 바다는?', '사랑해');
INSERT into aje_db (que, answer) VALUES('고개를 숙이고 눈물 흘리는 것은?', '수도꼭 지');
INSERT into aje_db (que, answer) VALUES('타는 것인데 앞뒤로 못 움직이는 것은?', '엘리베이터');
INSERT into aje_db (que, answer) VALUES('한쪽 발은 가만 있고 다른 발만 돌아다니는 것은?', '콤파스');
INSERT into aje_db (que, answer) VALUES('감인데 먹지 못하는 감은?', '영감');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 야한 닭은?', '홀닥');
INSERT into aje_db (que, answer) VALUES('진짜 문제투성이인 것은?', '시험지');
INSERT into aje_db (que, answer) VALUES('잘생긴 부처는?', '부처핸썸');
INSERT into aje_db (que, answer) VALUES('팥쥐의 깨진 독을 수리 해 준 사람은?', '독수리 오형제');
INSERT into aje_db (que, answer) VALUES('슈퍼맨의 가슴에"S"자는 무엇의 약자인가?', '스판');
INSERT into aje_db (que, answer) VALUES('내가 먹으면 맛이 없고 다른 사람이 먹어야 맛있는 탕은?', '골탕');
INSERT into aje_db (que, answer) VALUES('서울에 있는 대학을 무엇이라 하는가?', '서울대');
INSERT into aje_db (que, answer) VALUES('남의 눈으로 먹고 사는 사람은?', '안과의사');
INSERT into aje_db (que, answer) VALUES('늙을수록 몸이 고와지는 것은?', '과일');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 빨리 만들어지는 떡은?', '헐레벌떡');
INSERT into aje_db (que, answer) VALUES('하루 아침에 온 세상을 내다볼 수 있는 문은?', '신문');
INSERT into aje_db (que, answer) VALUES('다운로드의 반대말은?', '다웃은로드');
INSERT into aje_db (que, answer) VALUES('문을 두드리고 있는 여자를 다섯 글자로 하면?', '똑똑한 여자');
INSERT into aje_db (que, answer) VALUES('엄마가 길을 잃으면?', '맘마미아');
INSERT into aje_db (que, answer) VALUES('벌거벗은 남자를 그린 그림은?', '전라남도');
INSERT into aje_db (que, answer) VALUES('우리나라에서 김이 가장 많이 나는 곳은?', '목욕탕');
INSERT into aje_db (que, answer) VALUES('슈퍼마켓에서 일하는 남자를 세글자로 줄이면?', '슈퍼맨');
INSERT into aje_db (que, answer) VALUES('스님들이 걱정하지 않아도  되는 병은?', '탈모');
INSERT into aje_db (que, answer) VALUES('스캔들 하나 없는 연예인은?', '노사연');
INSERT into aje_db (que, answer) VALUES('개와 사람이 동업을 하면?', '개인사업');
INSERT into aje_db (que, answer) VALUES('먹지 않고 뱉는 약은?', '치약');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 더운 남자는?', '덥군');
INSERT into aje_db (que, answer) VALUES('신경통 환자가 가장 싫어하는 악기는?', '비올라');
INSERT into aje_db (que, answer) VALUES('하늘에 콩이 2개나 있다를 뭐라고 할까?', '스카이콩콩');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 착한 사자는?', '자원봉사자');
INSERT into aje_db (que, answer) VALUES('한 아이가 산에서 밑에 있는 할아버지에게 올라오라고 한 말은?', '산타할아버지');
INSERT into aje_db (que, answer) VALUES('수학책을 난로 위에 놓으 면?', '수학 익힘책');
INSERT into aje_db (que, answer) VALUES('둘리가 다니는 고등학교는?', '요리보고');
INSERT into aje_db (que, answer) VALUES('웃으면서 인사하다를 3글자로 하면?', '하이킥');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 추잡스럽기 짝이  없는 개는?', '꼴불견');
INSERT into aje_db (que, answer) VALUES('비가 오는 날에는 환자가 없다를 4글자로 줄이면?', '유비무환');
INSERT into aje_db (que, answer) VALUES('도둑이 훔친 돈을 뭐라고 할까?', '슬그머니');
INSERT into aje_db (que, answer) VALUES('옷을 가장 많이 해 입는 나라는?', '가봉');
INSERT into aje_db (que, answer) VALUES('달걀 장수가 달걀을 팔고 받은 돈은?', '에그머니');
INSERT into aje_db (que, answer) VALUES('울다가 다시 웃는 사람을 뭐라고 할까?', '아까운사람');
INSERT into aje_db (que, answer) VALUES('아프 지도 않는데 매일 집에서 쓰는 약은?', '치약');
INSERT into aje_db (que, answer) VALUES('추장보다 높은 사람은?', '고추장');
INSERT into aje_db (que, answer) VALUES('고추장보다 높은 사람은?', '초고추장');
INSERT into aje_db (que, answer) VALUES('초고추장보다 높은 사 람은?', '태양초고추장');
INSERT into aje_db (que, answer) VALUES('설경구가 녹으면?', '물경구');
INSERT into aje_db (que, answer) VALUES('미술학과 학생들이 타고 다니는 버스는?', '캔버스');
INSERT into aje_db (que, answer) VALUES('물고기 중 가장 학력이 좋은 물고기는?', '닥터피쉬');
INSERT into aje_db (que, answer) VALUES('꽃가게 주인이 가장 싫어하는 도시는?', '시드니');
INSERT into aje_db (que, answer) VALUES('"형이 용을 줬다"를 세글자로 하면?', '용준형');
INSERT into aje_db (que, answer) VALUES('화장실에 다녀온 원숭이를 뭐 라고 할까?', '일본원숭이');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 긍정적인 동물은?', '돼지');
INSERT into aje_db (que, answer) VALUES('정삼각형의 동생은?', '정삼각');
INSERT into aje_db (que, answer) VALUES('천주교 신자가 성당에서 예배드리는 일을 석자로 줄이면?', '미사일');
INSERT into aje_db (que, answer) VALUES('동물원에서 가장 비싼 동물은?', '백조');
INSERT into aje_db (que, answer) VALUES('미꾸라지의 반대말은?', '미꾸스몰');
INSERT into aje_db (que, answer) VALUES('담배만 있고 불이 없는 사람을 무엇이라고 하나?', '불필요한사람');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 잘하는 키퍼는?', '마그마');
INSERT into aje_db (que, answer) VALUES('거지가 싫어하는 색은?', '인색');
INSERT into aje_db (que, answer) VALUES('애플에서 나온 술은?', '맥주');
INSERT into aje_db (que, answer) VALUES('아이스크 림이 죽으면?', '다이하드');
INSERT into aje_db (que, answer) VALUES('왕과 작별인사를 뭐라고 할까?', '바이킹');
INSERT into aje_db (que, answer) VALUES('3월에 대학생이 강한 이유는?', '개강해서');
INSERT into aje_db (que, answer) VALUES('소가 한 마리면?', '소원');
INSERT into aje_db (que, answer) VALUES('소 가 두 마리면?', '투우');
INSERT into aje_db (que, answer) VALUES('소가 네 마리면?', '소포');
INSERT into aje_db (que, answer) VALUES('소가 여러 마리면?', '소스');
INSERT into aje_db (que, answer) VALUES('소가 죽으면?', '다이소');
INSERT into aje_db (que, answer) VALUES('김구선생님이 여자를 치면?', '여자친구');
INSERT into aje_db (que, answer) VALUES('침대를 밀고 돌리면?', '배드민턴');
INSERT into aje_db (que, answer) VALUES('김밥이 죽으면 어디로 갈까?', '김밥천국');
INSERT into aje_db (que, answer) VALUES('노인이 가장 좋아하는 폭포는?', '나이야가라');
INSERT into aje_db (que, answer) VALUES('사오정이 다니는 학교는?', '뭐라고');
INSERT into aje_db (que, answer) VALUES('도둑이 싫어하는 과자는?', '누네띠네');
INSERT into aje_db (que, answer) VALUES('미국에서 비가 내리면?', 'USB');
INSERT into aje_db (que, answer) VALUES('세상에서 가장 담배를 잘 피는 왕은?', '스모킹');
INSERT into aje_db (que, answer) VALUES('길 가다 나무를 주우면?', '우드득');
INSERT into aje_db (que, answer) VALUES('숫자 5가 싫어하는 집은?', '오페라하우스');
INSERT into aje_db (que, answer) VALUES('왕이 오른쪽에도 있고 왼쪽에도 있으면?', '우왕좌왕');
INSERT into aje_db (que, answer) VALUES('가나초콜릿 이 단 이유는?', '가나다라 (가나달아)');
INSERT into aje_db (que, answer) VALUES('닭의 부인은?', '닭처');
INSERT into aje_db (que, answer) VALUES('나무 다섯 그루는?', '오목');
INSERT into aje_db (que, answer) VALUES('토끼가 빗는 빗은?', '래빗');
INSERT into aje_db (que, answer) VALUES('말이 많은 사람은?', '목 장주인');
INSERT into aje_db (que, answer) VALUES('곰이 목욕을 하는 곳은?', '곰탕');
INSERT into aje_db (que, answer) VALUES('가장 멋없는 춤은?', '엉거주춤');
INSERT into aje_db (que, answer) VALUES('가장 황홀한 춤은?', '입맞춤');
INSERT into aje_db (que, answer) VALUES('펭귄이 신는 신발은?', '빙신');
INSERT into aje_db (que, answer) VALUES('낮 에만 가는 시계는?', '해시계');
INSERT into aje_db (que, answer) VALUES('육지에 사는 고래는?', '술고래');
INSERT into aje_db (que, answer) VALUES('작아도 크다고 하는 나무는?', '대나무');
INSERT into aje_db (que, answer) VALUES('만두 장수가 가장 싫어하는 말은?', '속터 져');
INSERT into aje_db (que, answer) VALUES('가장 엄숙하지 않은 절은?', '안절부절');
INSERT into aje_db (que, answer) VALUES('신혼부부가 좋아하는 곤충은?', '잠자리');
INSERT into aje_db (que, answer) VALUES('곰운 사과를 어떻게 먹을까?', '베어먹는다');
INSERT into aje_db (que, answer) VALUES('담배가 없는데 라이터만 있는 사람을 무엇이라고 하나?', '불만있는사람');
INSERT into aje_db (que, answer) VALUES('고추잠자리를 2글자로 줄이면?', '팬티');
INSERT into aje_db (que, answer) VALUES('삶은?', '달걀');
INSERT into aje_db (que, answer) VALUES('뚱뚱한 사람들이 모여있는 동네는?', '개포동');
INSERT into aje_db (que, answer) VALUES('덜 뚱뚱한 사람들이 모여있는 동네는?', '반포동');
INSERT into aje_db (que, answer) VALUES('돌잔치를 영어로 하면?', '락페스티벌');
INSERT into aje_db (que, answer) VALUES('깨가 죽으면?', '주근깨');
